storage:
  path: ${STORAGE_PATH:./uploads}

spring:
  application:
    name: document-qa-assistant

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: ${APP_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
